spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: rootpass
    url: jdbc:mysql://localhost:3306/football
  jpa:
    show-sql: true
  properties:
    hibernate:
      format_sql: true